name: Lint and Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make build-container
    
    - name: Lint Javascript
      run: make lint
      
    - name: Lint Styles
      run: make lint-css
    
    - name: Test Coverage
      run: make test-coverage     
